### ISSUE TITLE
NoSectionError: No section: 'api_tracker'

### ISSUE THREAD

**Issue by hannahk0123** [fepereiro/FirehoseWithComprehend#1]
I have a NoSectionError: api tracker. 
Do I supposed to type something else for 'api_tracker'? I deleted my access token below, but I have it in my file.  Can anyone help me resolving this error? What should I fix to get rid of this error?

Traceback (most recent call last):

  File "<ipython-input-37-de44cd6c1dd1>", line 21, in <module>
    access_token = parser.get('api_tracker', 'ACCESS TOCKEN ')

  File "//anaconda3/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)

  File "//anaconda3/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None

NoSectionError: No section: 'api_tracker'

**Comment by ladycatusa** [comment]
Hello,

I have the same error, I think there is something rowng in config parser in Python 3.


from configparser import SafeConfigParser
import configparser

parser = configparser.SafeConfigParser()
parser.read('api_auth.cfg')

#This is the super-secret information

access_token = parser.get(.....)

hopefully, the author will update to the new version
